[package]
name = "the_book"
version = "0.1.0"
authors = ["k_higuchi <koyohiguchi7788@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "1"
path = "src/01_hello_world/main.rs"

[dependencies]
